# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Generate static assets
      run: npm run build

    # Runs a set of commands using the runners shell
    - name: Deploy to gh-pages
      run: |
        cd dist
        git init
        git add -A
        git commit -m "deploy"
        git push -f https://github.com/FestiveAkp/clock.git master:gh-pages
        cd -
